// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_wGmlR5h5Cbl3lEvKqVO94Q6BE1veQP0',
    appId: '1:107861929323:web:7e5871cba25424ac69b02e',
    messagingSenderId: '107861929323',
    projectId: 'tracked-17c25',
    authDomain: 'tracked-17c25.firebaseapp.com',
    databaseURL: 'https://tracked-17c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracked-17c25.appspot.com',
    measurementId: 'G-BNT2X6RB3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypFrvOYdfBfbG9Sj6ptceFuPOixC_QJI',
    appId: '1:107861929323:android:74f31ee61f15362a69b02e',
    messagingSenderId: '107861929323',
    projectId: 'tracked-17c25',
    databaseURL: 'https://tracked-17c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracked-17c25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHU4Q4plpNaNkkiv6O5ko1CGM-pi59CAc',
    appId: '1:107861929323:ios:86d7a14e027747fe69b02e',
    messagingSenderId: '107861929323',
    projectId: 'tracked-17c25',
    databaseURL: 'https://tracked-17c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracked-17c25.appspot.com',
    iosBundleId: 'com.example.bikeRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHU4Q4plpNaNkkiv6O5ko1CGM-pi59CAc',
    appId: '1:107861929323:ios:b10e2d407513b5c269b02e',
    messagingSenderId: '107861929323',
    projectId: 'tracked-17c25',
    databaseURL: 'https://tracked-17c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tracked-17c25.appspot.com',
    iosBundleId: 'com.example.bikeRental.RunnerTests',
  );
}